export const baseMotionDefaults = {
  density: 1,
  speed: 1,
  trailAmount: 0.4,
  glitchAmount: 0.1,
  strength: 0.7,
  randomness: 0.3,
  frequency: 1,
  amplitude: 1,
  decay: 0.1,
  drag: 0.05,
  gravity: 0.5,
  noiseScale: 1,
  flowStrength: 0.8,
  symmetry: 6,
  petals: 5,
  spiralAmount: 0.5,
  cellularAmount: 0.5,
  scanlineAmount: 0.5,
};
